#include<bits/stdc++.h>
#include<iostream>
#include<vector>
#include<string>
#include<algorithm>
using namespace std;
void print(vector<char> &guessed, string generated){
    int cnt = 0;
    if(guessed.size()==0){
        for(int i=0;i<generated.length();i++){
            cout<<"- ";
        }
    }
    else{
        for(int i=0;i<generated.length();i++){
            bool flag = false;
            for(int j=0;j<guessed.size();j++){
                if(guessed[j]==generated[i]){
                    cout<<guessed[j]<<" ";
                    flag = true;
                }
            }
            if(!flag){
                cout<<"- ";
            }
        }
    }
}
bool check(char guess, string generated){
    for(int i=0;i<generated.size();i++){
        if(generated[i]==guess){
            return true;
        }
    }
    return false;
}
bool Won(vector<char> &guessed, string generated){
    int cnt = 0;
    for(int i=0;i<generated.length();i++){
            bool flag = false;
            for(int j=0;j<guessed.size();j++){
                if(guessed[j]==generated[i]){
                    cnt++;
             }
        }
    }
    if(cnt == generated.length()){
        return true;
    }
    return false;
}
int main(){
    string words[]= {"ANKUR","HARSHIT","PALU","ANNU","MANGO","APPLE","NUMBER","KITE","INDIA","FRANCE","JAPAN","PANAMA","RUSSIA","DELHI","BIKE","TATA","SPLENDID","OM","HINDU","HANUMAN","BANANA","ROLL","EGG","CHICKEN","PANNER","TOFU","ORANGE","SHIVA","SARASWATI","JEUS","ISRAEL","REPUBLIC","AFRICA","PHILLIPINES","POTATO","APPLE", "BOOK", "CAR", "DOG", "EGG", "FISH", "GRAPE", "HOUSE", "ICE", "JUICE", "KITE", "LEAF", "MOON", "NEST", "ORANGE", "PEN", "QUEEN", "ROSE", "SUN", "TREE", "UMBRELLA", "VASE", "WIND", "X-RAY", "YARN", "ZEBRA", "ANT", "BALL", "CAT", "DOOR", "EAR", "FROG", "GLASS", "HAT", "INK", "JACKET", "KEY", "LAMP", "MOUSE", "NOTE", "OWL", "PIZZA", "QUILT", "RING", "STAR", "TIGER", "UNIFORM", "VIOLIN", "WHALE", "XYLOPHONE", "YOGURT", "ZOO", "AIR", "BOAT", "CLOCK", "DOLL", "EARTH", "FAN", "GIFT", "HORSE", "IRON", "JUMP", "KITE", "LION"};
    srand((unsigned)time(0));
    int i = rand()%100;
    //cout<<i<<endl;
    string generated = words[i];
    char guess;
    int leftattempt = 6;
    bool ans = false;
    bool final = false;
    vector<char> guessed;
    cout<<"--------------------*WELCOME TO HANGMAN*--------------------"<<endl;
    cout<<"             SAVE YOUR FRIEND FROM BEING HANGGED       "<<endl;
    cout<<endl;
    cout<<"------------------------------------------------------------"<<endl;
    cout<<"| RULES OF THE GAME ARE AS FOLLOWS:                        |"<<endl;
    cout<<"| YOU HAVE TO GUESS THE LETTERS OF THE WORD GENERATED BY ME|"<<endl;
    cout<<"| YOU WILL BE GIVEN 6 ATTEMPTS TO GUESS THE WORD           |"<<endl;
    cout<<"| GUESS THE WORDS CORRECTLY TO SAVE YOUR FRIEND            |"<<endl;
    cout<<"|                                                          |"<<endl;
    cout<<"|                                                          |"<<endl;
    cout<<"|                 ENJOY PLAYING THE GAME >_<               |"<<endl;
    cout<<"------------------------------------------------------------"<<endl;
    while(leftattempt<=6){
        cout<<"You have"<<leftattempt<<" attempts left"<<endl;
        print(guessed,generated);
        cout<<endl;
        cin>>guess;
        if(find(guessed.begin(),guessed.end(),guess)!=guessed.end()){
            cout<<"You have already guessed "<<guess<<endl;
        }
        else{
        guessed.push_back(guess);
        }
        ans=check(guess,generated);
        
        if(Won(guessed,generated)){
            cout<<"You Won"<<endl;
            cout<<"The correct word was "<<generated<<endl;
            return 0;
        }
        if((ans)){
            cout<<"Correct Guess"<<endl;
        }
        if(!ans){
            leftattempt--;
            cout<<"Wrong guess"<<endl;
        }
        if(leftattempt == 0){
            cout<<"You Lost"<<endl;
            cout<<"The correct word was "<<generated<<endl;
            break;
        }
    }
    return 0;
}